name: Build Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v4

      - name: Checkout Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout Theos SDKs
        uses: actions/checkout@v4
        with:
          repository: theos/sdks
          ref: master
          path: theos/sdks

      - name: Compile Dylib
        run: |
          export THEOS="${{ github.workspace }}/theos"
          chmod -R 755 .
          set -o pipefail
          make FINALPACKAGE=1 THEOS="${{ github.workspace }}/theos" 2>&1 | tee make.log || {
            echo "### ❌ Build Error Log" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -n 120 make.log >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          }

      - name: Upload Dylib Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 34306jit-Dylib
          path: |
            .theos/obj/*.dylib
            .theos/obj/**/*.dylib
            packages/*.deb
            make.log
